name: app_chiseletor
description: "a flutter package aims on reducing basic app dev procedures"
# publish_to: 'none'
version: 1.0.0+1

homepage: https://github.com/Yunitrish006006/AppChiseletor/tree/main

environment:
  sdk: ^3.7.0-209.1.beta
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/