name: app_chiseletor
description: A Flutter framework with theme management, authentication, and localization support.
version: 1.0.0+1
homepage: https://github.com/Yunitrish006006/AppChiseletor
repository: https://github.com/Yunitrish006006/AppChiseletor
documentation: https://github.com/Yunitrish006006/AppChiseletor/tree/main#readme
issue_tracker: https://github.com/Yunitrish006006/AppChiseletor/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.4.0
  nested: ^1.0.0
  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated