name: app_chiseletor
description: A comprehensive Flutter framework that provides seamless integration of theme management, Firebase authentication (Email, Google Sign-in), and multilingual support (en, zh, zh_TW). Features include custom theme creation, dark mode support, and persistent authentication state.
version: 1.1.5+7
homepage: https://github.com/Yunitrish006006/AppChiseletor
repository: https://github.com/Yunitrish006006/AppChiseletor
documentation: https://github.com/Yunitrish006006/AppChiseletor/tree/main#readme
issue_tracker: https://github.com/Yunitrish006006/AppChiseletor/issues

# 支援的平台
platforms:
  android: null
  ios: null
  web: null

# 主題標籤
topics:
  - theme
  - authentication
  - localization
  - firebase
  - flutter-widgets

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  nested: ^1.0.0
  
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_gen:
  output: lib/gen/
  line_length: 120

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated

# 添加 false_secrets 配置以忽略 Firebase 憑證警告
false_secrets:
  - example/android/app/google-services.json
  - example/lib/firebase_options.dart